---
- name: Remove prior data and volume folders
  command: "sudo rm -Rf {{ volumes_dir }}/{{ item }}"
  args:
    removes: "{{ volumes_dir }}/{{ item }}"
  with_items:
    - quay-redis
    - quay-postgresql
    - quay-storage
    - quay-config
    - clair-postgresql
    - clair-config
    - quay-builder
    - certs

- name: Create volume folders
  file:
    path: "{{ volumes_dir }}/{{ item }}"
    state: directory
  with_items:
    - quay-redis
    - quay-postgresql
    - quay-storage
    - quay-config
    - clair-postgresql
    - clair-config
    - quay-builder
    - certs

- name: Remove old Downloads
  file:
    path: "{{ downloads_dir }}/{{ item }}"
    state: absent
  with_items:
    - quay-config.tar.gz
    - security_scanner.pem

- name: Create TLS cert and key
  shell:
    cmd: |
      # Root CA
      openssl genrsa -out {{ volumes_dir }}/certs/rootCA.key 4096
      openssl req -new -x509 -key {{ volumes_dir }}/certs/rootCA.key -out {{ volumes_dir }}/certs/rootCA.crt \
          -days 365 -extensions v3_ca -subj "/C=US/L=Syracuse/CN=Quay"

      # Quay server
      openssl genrsa -out {{ volumes_dir }}/certs/quay.key 4096
      openssl req -new -key {{ volumes_dir }}/certs/quay.key -out {{ volumes_dir }}/certs/quay.csr \
          -subj "/C=US/ST=New York/L=Cazenovia/O=Red Hat/OU=Quay/emailAddress=thomasmckay@redhat.com/CN={{ quay_host }}"
      openssl x509 -req -days 365 -in {{ volumes_dir }}/certs/quay.csr -out {{ volumes_dir }}/certs/quay.crt \
          -CA {{ volumes_dir }}/certs/rootCA.crt -CAkey {{ volumes_dir }}/certs/rootCA.key \
          -CAcreateserial -extensions v3_req -extfile /etc/pki/tls/openssl.cnf

      # Clair server
      openssl genrsa -out {{ volumes_dir }}/certs/clair.key 4096
      openssl req -new -key {{ volumes_dir }}/certs/clair.key -out {{ volumes_dir }}/certs/clair.csr \
          -subj "/C=US/ST=New York/L=Cazenovia/O=Red Hat/OU=Quay/emailAddress=thomasmckay@redhat.com/CN={{ quay_host }}"
      openssl x509 -req -days 365 -in {{ volumes_dir }}/certs/clair.csr -out {{ volumes_dir }}/certs/clair.crt \
          -CA {{ volumes_dir }}/certs/rootCA.crt -CAkey {{ volumes_dir }}/certs/rootCA.key \
          -CAcreateserial -extensions v3_req -extfile /etc/pki/tls/openssl.cnf

- name: Install rootCA and restart docker.service
  shell:
    cmd: |
      sudo cp {{ volumes_dir }}/certs/rootCA.crt /etc/pki/ca-trust/source/anchors
      sudo update-ca-trust extract
      sudo systemctl restart docker.service