---
- name: Pull latest image
  shell:
    cmd: |
      docker pull {{ quay_image }}

- name: Quay Registry container
  docker_container:
    name: quay
    image:  "{{ quay_image }}"
    volumes:
      - "{{ volumes_dir }}/quay-config:/conf/stack"
      - "{{ volumes_dir }}/quay-storage:/datastorage"
    env:
      QUAYENTRY: registry
      DEBUGLOG: "true"
    ports:
      - "80:8080"
      - "443:8443"
    etc_hosts:
      "{{ quay_host }}:{{ quay_ip }}"
    keep_volumes: true
    auto_remove: true
    state: started
    restart: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
