apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quays.quay.io
spec:
  group: quay.io
  names:
    kind: Quay
    listKind: QuayList
    plural: quays
    singular: quay
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
